#!/bin/bash

if [[ $# -eq 0 ]]; then
	echo "file text:/ \"Generic Text Backend\" \"Generic Text Backend\""
	exit 0
fi

if [[ $# -eq 6 ]]; then
    echo "Output $6"
    cat $6 > /tmp/output.txt
else
    echo "Output from stdin"
    cat - > /tmp/output.txt
fi

exit 0
