FROM xlate/karaf
MAINTAINER Michael Edgar, www.xlate.io

ADD org.apache.activemq.server-default.cfg ${KARAF_BASE}/etc 
ADD org.apache.activemq.webconsole.cfg     ${KARAF_BASE}/etc 
ADD activemq-5.13.3-features.xml           ${KARAF_BASE}/deploy 
